version: 4.41.0
project:
  name: "CineBook"
  type: "brownfield"
  framework: "fullstack"
  description: "Hệ thống đặt vé xem phim trực tuyến với ReactJS 18 và Laravel 10"

workflow: "brownfield-fullstack"

docs:
  prd:
    file: "docs/prd.md"
    version: "v4"
    sharded: true
    shardedLocation: "docs/epics"
    epicFilePattern: "epic-*.md"
  
  architecture:
    file: "docs/architecture.md"
    version: "v4"
    sharded: true
    shardedLocation: "docs/architecture"
  
  stories:
    location: "docs/stories"
  
  qa:
    location: "docs/qa"

technology:
  frontend:
    framework: "React"
    version: "18"
    language: "TypeScript"
    stateManagement: "Context API"
    routing: "React Router"
    httpClient: "Axios"
    testing: "Vitest"
    
  backend:
    framework: "Laravel"
    version: "10"
    language: "PHP"
    authentication: "Laravel Sanctum"
    database: "MySQL"
    cache: "Redis"
    queue: "Laravel Queue"
    testing: "PHPUnit"

agents:
  default: "bmad-master"
  available:
    - "bmad-master"
    - "bmad-orchestrator"
    - "dev"
    - "qa"
    - "sm"
    - "po"
    - "architect"

rules:
  projectRules: ".qoder/rules/01-project.md"
  alwaysLoad: true

customCommands:
  - name: "start-frontend"
    command: "cd frontend && npm run dev"
    description: "Start React development server"
  
  - name: "start-backend"
    command: "cd backend && php artisan serve"
    description: "Start Laravel development server"
  
  - name: "run-tests"
    command: "cd backend && php artisan test && cd ../frontend && npm run test"
    description: "Run both backend and frontend tests"

slashPrefix: "BMad"
markdownExploder: true
devDebugLog: ".ai/debug-log.md"